version: "3"
services:
  jenkins:
    build: ./docker/jenkins
    container_name: jenkins
#    image: jenkins/jenkins:lts
    volumes:
      - ./data/jenkins/:/var/jenkins_home
      - ./data/ansible:/etc/ansible
      - ./script:/opt/script
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
      - "8888:8080"
      - "50000:50000"
    expose:
      - "8080"
      - "50000"
    privileged: true
    user: root
    # restart: always
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'

    networks:
        - jenkins_net

networks:
  jenkins_net:
    driver: bridge
