version: "3.6"
services:
  flowableidm:
    image: flowable/flowable-idm:6.5.0
    ports:
     - "9090:9090"
    environment:
      SERVER_PORT: 9090
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flow
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
      FLOWABLE_REST_APP_ADMIN_USER-ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
      FLOWABLE_REST_APP_ADMIN_FIRST-NAME: Rest
      FLOWABLE_REST_APP_ADMIN_LAST-NAME: Admin
    expose: 
      - "9090"
  
  flowabletask:
    image: flowable/flowable-task:6.5.0
    ports: 
      - "9080:9080"
    environment:
      SERVER_PORT: 9080
      FLOWABLE_COMMON_APP_IDM-URL: http://172.16.12.11:9090/flowable-idm
      FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
      FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://172.16.12.11:9090/flowable-idm
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flow
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
    expose: 
      - "9080"

  flowablemodeler:
    image: flowable/flowable-modeler:6.5.0
    ports:
      - "9070:9070"
    environment:
      SERVER_PORT: 9070
      FLOWABLE_COMMON_APP_IDM-URL: http://172.16.12.11:9090/flowable-idm
      FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
      FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://172.16.12.11:9090/flowable-idm
      FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL: http://172.16.12.11:9080/flowable-task/app-api
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flow
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
    expose: 
      - "9070"
  
  flowablerest:
    image: flowable/flowable-rest:6.5.0
    ports:
      - "9060:9060"
    environment:
      SERVER_PORT: 9060
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flow
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
      FLOWABLE_REST_APP_ADMIN_USER-ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
      FLOWABLE_REST_APP_ADMIN_FIRST-NAME: Rest
      FLOWABLE_REST_APP_ADMIN_LAST-NAME: Admin
    expose: 
      - "9060"

  flowableadmin:
    image: flowable/flowable-admin:6.5.0
    ports:
      - "9050:9050"
    environment:
      SERVER_PORT: 9050
      FLOWABLE_COMMON_APP_IDM-URL: http://172.16.12.11:9090/flowable-idm
      FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
      FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://172.16.12.11:9090/flowable-idm
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flow
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
      FLOWABLE_REST_APP_ADMIN_USER-ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT: service
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT: cmmn-api
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT: dmn-api
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT: form-api
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT: content-api
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS: http://172.16.12.11
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT: 9060
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT: flowable-rest
      FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT: app-api
    expose: 
      - "9050"
               
