version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      TZ: Asia/Shanghai
      # mysql root用户密码
      MYSQL_ROOT_PASSWORD: 123456
    command:
# 8.0默认使用加密插件是caching_sha2_password
# https://blog.csdn.net/sinat_41632924/article/details/113251336
#      --default-authentication-plugin=mysql_native_password
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    volumes:
      # mysql的数据文件
      - ./data/mysql/data:/var/lib/mysql
      # mysql配置文件
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/mysql-init-files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

