version: "3.6"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "8081:8081"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/data:/data
      - ./data/nginx/log:/var/log/nginx
    networks:
        - nginx_net

networks:
  nginx_net:
    driver: bridge
