version: "3.6"

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${FS_REDIS_PORT}:${FS_REDIS_PORT}"
    environment:
      FS_REDIS_PORT: ${FS_REDIS_PORT}
      FS_REDIS_PASSWORD: ${FS_REDIS_PASSWORD}
    volumes:
#      - ./data/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: redis-server --port ${FS_REDIS_PORT}  --requirepass ${FS_REDIS_PASSWORD}
#    command: redis-server /etc/redis/redis.conf
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - "./data/minio/data1-1:/data1"
      - "./data/minio/data1-2:/data2"

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - "./data/minio/data2-1:/data1"
      - "./data/minio/data2-2:/data2"

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - "./data/minio/data3-1:/data1"
      - "./data/minio/data3-2:/data2"

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - "./data/minio/data4-1:/data1"
      - "./data/minio/data4-2:/data2"

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - "./data/minio/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      FS_MINIO_PORT: ${FS_MINIO_PORT}
      FS_MINIO_CONSOLE_PORT: ${FS_MINIO_CONSOLE_PORT}
    ports:
      - "${FS_MINIO_PORT}:9000"
      - "${FS_MINIO_CONSOLE_PORT}:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
  fs:
    build: ./docker/fs
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev/fuse'
    security_opt:
      - apparmor:unconfined
    container_name: fs
    restart: always
    ports:
      - "8802:8802"   
    volumes:
      - ./data/openresty/conf.d:/etc/nginx/conf.d
      - ./data/openresty/html:/usr/local/openresty/nginx/html
      - ./data/openresty/log:/var/log
      - ./data/openresty/lua:/usr/local/openresty/nginx/lua
    command: /bin/bash -c "/usr/local/openresty/bin/openresty -t;/usr/local/openresty/bin/openresty;juicefs format --storage minio --bucket http://nginx:${FS_MINIO_PORT}/${FS_MINIO_BUCKET} --access-key ${FS_MINIO_USER} --secret-key ${FS_MINIO_PASSWORD} redis://:${FS_REDIS_PASSWORD}@redis:${FS_REDIS_PORT}/${FS_REDIS_DB} ${FS_MINIO_BUCKET};juicefs mount  redis://:${FS_REDIS_PASSWORD}@redis/${FS_REDIS_DB} /opt/fs;"
    depends_on:
      - redis
      - nginx

## By default this config uses default local driver,
### For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: 
