version: "3.6"
services:
  flowable-all:
    image: flowable/all-in-one
    ports:
     - "8080:8080"
    environment:
      SERVER_ADDRESS: 172.16.12.11
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.16.12.11:5432/flowable
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev123
      FLOWABLE_COMMON_APP_IDM-URL: http://172.16.12.11:8080/flowable-idm
      FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
      FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://172.16.12.11:8080/flowable-idm
      FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL: http://172.16.12.11:8080/flowable-task/app-api
      FLOWABLE_REST_APP_ADMIN_USER-ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
