# https://github.com/AmosWang0626/docker-dubbo/blob/master/docker-compose.yml
version: '3.5'

services:
  zoo1:
    image: zookeeper:3.4.13
    restart: always
    container_name: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - dubbo-net

  zoo2:
    image: zookeeper:3.4.13
    restart: always
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - dubbo-net

  zoo3:
    image: zookeeper:3.4.13
    restart: always
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - dubbo-net

  dubbo-admin:
    image: apache/dubbo-admin
    container_name: dubbo
    ports:
      - 8090:8080
    networks:
      - dubbo-net
    environment:
      - admin.registry.address=zookeeper://zoo1:2181?backup=zoo2:2181,zoo3:2181
      - admin.config-center=zookeeper://zoo1:2181?backup=zoo2:2181,zoo3:2181
      - admin.metadata-report.address=zookeeper://zoo1:2181?backup=zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3

networks:
  dubbo-net:
    name: dubbo-net
    driver: bridge
