version: '2'
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    volumes:
      - ~/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev_user #在此填写postgres的用户名
      POSTGRES_DB: postgres #在此填写postgres的数据库名，默认是postgres
      POSTGRES_PASSWORD: dev123 #在此填写posgres的数据库密码
    ports:
      - "5432:5432"
    networks:
        - pg_net

networks:
  pg_net:
    driver: bridge
