version: "3.6"
services:
  fs:
    build: ./docker/fs
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev/fuse'
    security_opt:
      - apparmor:unconfined
    container_name: fs
    restart: always
    ports:
      - "8800:80"
      - "8801:8801"
      - "8802:8802"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/openresty/conf.d:/etc/nginx/conf.d
      - ./data/openresty/html:/usr/local/openresty/nginx/html
      - ./data/openresty/log:/var/log
      - ./data/openresty/lua:/usr/local/openresty/nginx/lua
      - ./script/init.sh:/init.sh
    command: sh -c "/init.sh;"
